server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.115.203.179:3306/driving_school?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
mybatis-plus:
  #??Mapper????
  mapper-locations: classpath:mapper/*.xml
  # ??Mybatis?????????????????
  type-aliases-package: com.example.pojo
logging:
  level:
    com:
      sac:
        demo:
          mapper : debug